recipes: switchdev: Prevent error when no RED backlog
When no backlog exists, Python might provide the following traceback:

	File "/usr/share/lnst/recipes/switchdev/qos-018-prio_red_remapping_change_size.py",
	line 39, in do_task
		red_test.check_red_high(high_red_res)

	File "/usr/share/lnst/recipes/switchdev/RedTestLib.py", line 313, in
	check_red_high
		if max(res.backlogs) > self.max * 1.2:

	ValueError: max() arg is an empty sequence

Fixes: 8b9fe622b653 ("recipes: switchdev: RedTestLib: Add backlog check")
Signed-off-by: Yuval Mintz <yuvalm@mellanox.com>